### ISSUE TITLE
[Insight] Symfony applications should not contain a config.php file - in web, line 0

### ISSUE THREAD

**Issue by lumilo8** [sopinet/BasicSymfony#14]
**[in web](https://github.com/sopinet/BasicSymfony/blob/9993b8a666931c2b1daeb8c291e7b268454438ba/web#L0)**

> This `config.php` file should only be used to bootstrap a Symfony application. Before releasing to production, you should remove it, otherwise attackers could get valuable insight about your application.

```

web/
├── app.php
├── app_dev.php
├── apple-touch-icon.png
├── config.php
├── favicon.ico
└── robots.txt
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/84f19b4e-6135-457d-be83-56b684231595/analyses/33)_

**Comment by lumilo8** [comment]
Done

**Comment by molinan2** [comment]
I think this should not be removed from BasicSymfony, since BasicSymfony is intended to aid in the development and not being a fully featured application. `config.php` may be usefull to anyone who try this bundle and thus should not be removed.

Removing `config.php` should only be done in production.

**Comment by lumilo8** [comment]
You're right, i'm going to restored it and i have modificated the SensioLabsInsight rules in order to skip this warning, thanks
